### ISSUE TITLE
Consider twitter integration

### ISSUE THREAD

**Issue by theoretick** [theoretick/discuss-it#73]
This could be totally badass. I just thought about querying twitter's API for tweets that include the given URL.  We can intersperse them either chronologically or if the API supports linked tweets (i.e. replies and retweets) include those as discussion threads.

Far, far future idea: If this ever evolves to the 'intersperse comments' phase of combining individual posts into a singular thread we host, then this would work perfectly as well

**Comment by CodingAntecedent** [comment]
v0.1 of this feature could use https://dev.twitter.com/rest/reference/get/search/tweets it already filters by relevance so we could probably just return the top tweet, if any.

**Comment by theoretick** [comment]
oooh fun!
